# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteracaoContato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('tipo', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField()),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TarefaContato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoCRM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('telefone', models.CharField(db_index=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(db_index=True, max_length=120)),
                ('bairro', models.CharField(blank=True, db_index=True, max_length=120)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('zona_eleitoral', models.CharField(blank=True, max_length=20)),
                ('secao_eleitoral', models.CharField(blank=True, max_length=20)),
                ('origem_contato', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status_funil', models.CharField(choices=[('novo_contato', 'Novo contato'), ('primeiro_atendimento', 'Primeiro atendimento'), ('em_relacionamento', 'Em relacionamento'), ('interessado', 'Interessado'), ('apoiador', 'Apoiador'), ('voluntario', 'Voluntário'), ('lideranca', 'Liderança'), ('inativo', 'Inativo')], default='novo_contato', max_length=25)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('observacoes', models.TextField(blank=True)),
                ('data_primeiro_contato', models.DateTimeField(blank=True, null=True)),
                ('data_ultimo_contato', models.DateTimeField(blank=True, null=True)),
                ('proxima_acao', models.CharField(blank=True, max_length=255)),
                ('consentimento_comunicacao', models.BooleanField(default=False)),
                ('canal_autorizado', models.CharField(blank=True, max_length=40)),
                ('data_consentimento', models.DateTimeField(blank=True, null=True)),
                ('possivel_duplicado', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
            ],
            options={
                'verbose_name': 'Contato CRM',
                'verbose_name_plural': 'Contatos CRM',
            },
        ),
    ]
