# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleitores', '0001_initial'),
        ('liderancas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatocrm',
            name='lideranca_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_relacionados', to='liderancas.lideranca'),
        ),
    ]
