# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0002_initial'),
        ('eleitores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contatocrm',
            name='responsavel_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_cadastrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interacaocontato',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='interacaocontato',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='eleitores.contatocrm'),
        ),
        migrations.AddField(
            model_name='interacaocontato',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_contatos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarefacontato',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='tarefacontato',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='eleitores.contatocrm'),
        ),
        migrations.AddField(
            model_name='tarefacontato',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_contato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contatocrm',
            index=models.Index(fields=['nome_completo'], name='eleitores_c_nome_co_738a45_idx'),
        ),
        migrations.AddIndex(
            model_name='contatocrm',
            index=models.Index(fields=['telefone', 'email'], name='eleitores_c_telefon_33e844_idx'),
        ),
        migrations.AddIndex(
            model_name='contatocrm',
            index=models.Index(fields=['cidade', 'bairro'], name='eleitores_c_cidade_7c5cbe_idx'),
        ),
    ]
