# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logseguranca',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha'),
        ),
    ]
