# Generated by Django 6.0.7 on 2026-07-28 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_initial'),
        ('campanhas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logseguranca',
            options={'verbose_name': 'Log de segurança', 'verbose_name_plural': 'Logs de segurança'},
        ),
        migrations.AlterModelOptions(
            name='registroauditoria',
            options={'verbose_name': 'Registro de auditoria', 'verbose_name_plural': 'Registros de auditoria'},
        ),
        migrations.AlterField(
            model_name='logseguranca',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_seguranca', to='campanhas.campanha'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to='campanhas.campanha'),
        ),
        migrations.AddIndex(
            model_name='logseguranca',
            index=models.Index(fields=['evento', 'criado_em'], name='auditoria_l_evento_ff210a_idx'),
        ),
        migrations.AddIndex(
            model_name='logseguranca',
            index=models.Index(fields=['severidade', 'criado_em'], name='auditoria_l_severid_29786b_idx'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['modelo', 'objeto_id'], name='auditoria_r_modelo_e0db67_idx'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['acao', 'criado_em'], name='auditoria_r_acao_2383ca_idx'),
        ),
    ]
