# Generated by Django 6.0.7 on 2026-07-28 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_alter_logseguranca_options_and_more'),
        ('campanhas', '0002_initial'),
        ('eleitores', '0003_initial'),
        ('liderancas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logseguranca',
            options={'verbose_name': 'Log de seguranca', 'verbose_name_plural': 'Logs de seguranca'},
        ),
        migrations.CreateModel(
            name='PoliticaRetencaoDados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo_registro', models.CharField(choices=[('contatos', 'Contatos'), ('liderancas', 'Liderancas'), ('eventos', 'Eventos'), ('equipe', 'Equipe'), ('metas', 'Metas'), ('financeiro', 'Financeiro'), ('comunicacao', 'Comunicacao'), ('auditoria', 'Auditoria'), ('seguranca', 'Seguranca')], db_index=True, max_length=30)),
                ('base_legal', models.CharField(blank=True, max_length=120)),
                ('dias_retencao', models.PositiveIntegerField(default=365)),
                ('dias_ate_anonimizacao', models.PositiveIntegerField(default=0)),
                ('anonimizar_ao_expirar', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politicas_retencao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Politica de retencao',
                'verbose_name_plural': 'Politicas de retencao',
                'indexes': [models.Index(fields=['tipo_registro'], name='auditoria_p_tipo_re_6038f2_idx'), models.Index(fields=['campanha', 'tipo_registro'], name='auditoria_p_campanh_dbe92a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoTitularDados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome_solicitante', models.CharField(max_length=255)),
                ('email_solicitante', models.EmailField(blank=True, max_length=254)),
                ('telefone_solicitante', models.CharField(blank=True, max_length=20)),
                ('canal_origem', models.CharField(blank=True, max_length=60)),
                ('tipo_solicitacao', models.CharField(choices=[('acesso', 'Acesso'), ('correcao', 'Correcao'), ('anonimizacao', 'Anonimizacao'), ('exclusao', 'Exclusao logica'), ('revogacao_consentimento', 'Revogacao de consentimento')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_analise', 'Em analise'), ('concluida', 'Concluida'), ('negada', 'Negada')], db_index=True, default='aberta', max_length=20)),
                ('descricao', models.TextField()),
                ('prazo_resposta', models.DateField(blank=True, null=True)),
                ('resposta_interna', models.TextField(blank=True)),
                ('executado_em', models.DateTimeField(blank=True, null=True)),
                ('resultado_execucao', models.TextField(blank=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
                ('contato_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_titular', to='eleitores.contatocrm')),
                ('lideranca_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_titular', to='liderancas.lideranca')),
                ('responsavel_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_titular_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitacao do titular',
                'verbose_name_plural': 'Solicitacoes dos titulares',
                'indexes': [models.Index(fields=['tipo_solicitacao', 'status'], name='auditoria_s_tipo_so_0c6e1b_idx'), models.Index(fields=['prazo_resposta'], name='auditoria_s_prazo_r_92b859_idx')],
            },
        ),
    ]
