# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroFavoritoRelatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome', models.CharField(max_length=120)),
                ('tipo_relatorio', models.CharField(db_index=True, max_length=60)),
                ('filtros', models.JSONField(default=dict)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
