# Generated by Django 6.0.7 on 2026-07-28 01:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('visita', 'Visita'), ('caminhada', 'Caminhada'), ('entrevista', 'Entrevista'), ('gravacao', 'Gravação'), ('compromisso', 'Compromisso do candidato'), ('acao_rua', 'Ação de rua'), ('evento_interno', 'Evento interno'), ('prazo', 'Prazo importante')], max_length=25)),
                ('data', models.DateField()),
                ('horario_inicial', models.TimeField()),
                ('horario_final', models.TimeField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('link_localizacao', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('prioridade', models.CharField(default='media', max_length=15)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('observacoes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Evento de agenda',
                'verbose_name_plural': 'Eventos de agenda',
            },
        ),
    ]
