# Generated by Django 6.0.7 on 2026-07-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('liderancas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='liderancas_convidadas',
            field=models.ManyToManyField(blank=True, related_name='eventos_convidados', to='liderancas.lideranca'),
        ),
    ]
