# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoagenda',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos_participando', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoagenda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventoagenda',
            index=models.Index(fields=['data', 'status'], name='agenda_even_data_43851f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoagenda',
            index=models.Index(fields=['tipo'], name='agenda_even_tipo_e0ab8d_idx'),
        ),
    ]
