# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaEquipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('prioridade', models.CharField(default='media', max_length=15)),
                ('status', models.CharField(choices=[('a_fazer', 'A fazer'), ('em_andamento', 'Em andamento'), ('em_revisao', 'Em revisão'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='a_fazer', max_length=20)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('comentarios', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tarefa de equipe',
                'verbose_name_plural': 'Tarefas de equipe',
            },
        ),
        migrations.CreateModel(
            name='IntegranteEquipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipe/fotos/')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('funcao', models.CharField(max_length=120)),
                ('departamento', models.CharField(db_index=True, max_length=120)),
                ('cidade_regiao', models.CharField(blank=True, db_index=True, max_length=120)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('disponibilidade', models.CharField(blank=True, max_length=120)),
                ('observacoes', models.TextField(blank=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
                ('responsavel_direto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='equipe.integranteequipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
