# Generated by Django 6.0.7 on 2026-07-28 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_initial'),
        ('equipe', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioTarefaEquipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('conteudo', models.TextField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_tarefas_equipe', to=settings.AUTH_USER_MODEL)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_registrados', to='equipe.tarefaequipe')),
            ],
            options={
                'verbose_name': 'Comentario de tarefa',
                'verbose_name_plural': 'Comentarios de tarefas',
                'indexes': [models.Index(fields=['tarefa', 'criado_em'], name='equipe_come_tarefa__d85430_idx'), models.Index(fields=['autor', 'criado_em'], name='equipe_come_autor_i_9d636e_idx')],
            },
        ),
    ]
