# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
import django.utils.timezone
import usuarios.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('nome_completo', models.CharField(max_length=255)),
                ('nome_exibicao', models.CharField(blank=True, max_length=120)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/')),
                ('nivel_acesso', models.CharField(choices=[('administrador', 'Administrador'), ('coordenador_geral', 'Coordenador-geral'), ('coordenador_regional', 'Coordenador regional'), ('financeiro', 'Financeiro'), ('comunicacao', 'Comunicação'), ('mobilizador', 'Mobilizador'), ('voluntario', 'Voluntário'), ('visualizador', 'Visualizador')], db_index=True, default='visualizador', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultimo_acesso_registrado', models.DateTimeField(blank=True, null=True)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('tentativas_falhas', models.PositiveIntegerField(default=0)),
                ('dois_fatores_habilitado', models.BooleanField(default=False)),
                ('tema_escuro', models.BooleanField(default=False)),
                ('consentimento_privacidade', models.BooleanField(default=False)),
                ('data_consentimento_privacidade', models.DateTimeField(blank=True, null=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_vinculados', to='campanhas.campanha')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'abstract': False,
                'indexes': [models.Index(fields=['email'], name='usuarios_us_email_41a027_idx'), models.Index(fields=['nivel_acesso'], name='usuarios_us_nivel_a_37fc5e_idx'), models.Index(fields=['campanha'], name='usuarios_us_campanh_9e5820_idx')],
            },
            managers=[
                ('objects', usuarios.managers.UsuarioManager()),
            ],
        ),
    ]
