# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0002_initial'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='responsavel_lancamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parceirofinanceiro',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.parceirofinanceiro'),
        ),
    ]
