# Generated by Django 6.0.7 on 2026-07-28 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_initial'),
        ('financeiro', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriafinanceira',
            options={'verbose_name': 'Categoria financeira', 'verbose_name_plural': 'Categorias financeiras'},
        ),
        migrations.AlterModelOptions(
            name='centrocusto',
            options={'verbose_name': 'Centro de custo', 'verbose_name_plural': 'Centros de custo'},
        ),
        migrations.AlterModelOptions(
            name='lancamentofinanceiro',
            options={'verbose_name': 'Lancamento financeiro', 'verbose_name_plural': 'Lancamentos financeiros'},
        ),
        migrations.AlterModelOptions(
            name='parceirofinanceiro',
            options={'verbose_name': 'Parceiro financeiro', 'verbose_name_plural': 'Parceiros financeiros'},
        ),
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('doacao', 'Doacao')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='centrocusto',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('liquidado', 'Liquidado'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('doacao', 'Doacao')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='parceirofinanceiro',
            name='tipo',
            field=models.CharField(choices=[('fornecedor', 'Fornecedor'), ('doador', 'Doador'), ('prestador', 'Prestador'), ('outro', 'Outro')], db_index=True, default='fornecedor', max_length=20),
        ),
        migrations.AddIndex(
            model_name='categoriafinanceira',
            index=models.Index(fields=['nome'], name='financeiro__nome_54330c_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriafinanceira',
            index=models.Index(fields=['tipo'], name='financeiro__tipo_492fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['nome'], name='financeiro__nome_912adf_idx'),
        ),
        migrations.AddIndex(
            model_name='centrocusto',
            index=models.Index(fields=['codigo'], name='financeiro__codigo_61342b_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['tipo', 'status'], name='financeiro__tipo_85fea1_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_0af95b_idx'),
        ),
        migrations.AddIndex(
            model_name='lancamentofinanceiro',
            index=models.Index(fields=['data_pagamento'], name='financeiro__data_pa_b26afb_idx'),
        ),
        migrations.AddIndex(
            model_name='parceirofinanceiro',
            index=models.Index(fields=['nome'], name='financeiro__nome_cbf8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='parceirofinanceiro',
            index=models.Index(fields=['tipo'], name='financeiro__tipo_70964f_idx'),
        ),
    ]
