# Generated by Django 6.0.7 on 2026-07-28 01:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome_campanha', models.CharField(max_length=255)),
                ('nome_candidato', models.CharField(max_length=255)),
                ('cargo_disputado', models.CharField(choices=[('prefeito', 'Prefeito'), ('vereador', 'Vereador'), ('deputado_estadual', 'Deputado estadual'), ('deputado_federal', 'Deputado federal'), ('senador', 'Senador'), ('governador', 'Governador'), ('presidente', 'Presidente'), ('outro', 'Outro')], db_index=True, max_length=30)),
                ('partido', models.CharField(max_length=20)),
                ('numero_candidato', models.CharField(max_length=10)),
                ('estado', models.CharField(db_index=True, max_length=2)),
                ('municipio', models.CharField(db_index=True, max_length=120)),
                ('data_inicio', models.DateField()),
                ('data_eleicao', models.DateField()),
                ('situacao', models.CharField(choices=[('planejamento', 'Planejamento'), ('ativa', 'Ativa'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada')], default='planejamento', max_length=20)),
                ('foto_candidato', models.ImageField(blank=True, null=True, upload_to='campanhas/candidato/')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='campanhas/logotipos/')),
                ('cor_primaria', models.CharField(default='#0F172A', max_length=7)),
                ('cor_secundaria', models.CharField(default='#2563EB', max_length=7)),
                ('descricao', models.TextField(blank=True)),
                ('objetivos_gerais', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
            },
        ),
    ]
