# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='coordenador_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_coordenadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='campanha',
            index=models.Index(fields=['nome_campanha'], name='campanhas_c_nome_ca_a4b067_idx'),
        ),
        migrations.AddIndex(
            model_name='campanha',
            index=models.Index(fields=['nome_candidato'], name='campanhas_c_nome_ca_c66506_idx'),
        ),
        migrations.AddIndex(
            model_name='campanha',
            index=models.Index(fields=['estado', 'municipio'], name='campanhas_c_estado_bb51b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='campanha',
            constraint=models.UniqueConstraint(fields=('numero_candidato', 'data_eleicao', 'municipio'), name='campanha_numero_eleicao_municipio_unico'),
        ),
    ]
