# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaBloqueio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('canal', models.CharField(max_length=30)),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModeloMensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome', models.CharField(max_length=120)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('conteudo', models.TextField()),
                ('canal', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampanhaComunicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome', models.CharField(max_length=255)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('conteudo', models.TextField()),
                ('canal', models.CharField(db_index=True, max_length=30)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('enviando', 'Enviando'), ('concluida', 'Concluída'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('quantidade_programada', models.PositiveIntegerField(default=0)),
                ('quantidade_enviada', models.PositiveIntegerField(default=0)),
                ('quantidade_entregue', models.PositiveIntegerField(default=0)),
                ('quantidade_falha', models.PositiveIntegerField(default=0)),
                ('quantidade_respostas', models.PositiveIntegerField(default=0)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
