# Generated by Django 6.0.7 on 2026-07-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunicacao', '0001_initial'),
        ('eleitores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhacomunicacao',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='campanhas_comunicacao', to='eleitores.contatocrm'),
        ),
    ]
