# Generated by Django 6.0.7 on 2026-07-28 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_initial'),
        ('comunicacao', '0003_initial'),
        ('eleitores', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioComunicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('notificacao_interna', 'Notificacao interna')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('falha', 'Falha'), ('respondido', 'Respondido'), ('cancelado', 'Cancelado')], db_index=True, default='programado', max_length=20)),
                ('mensagem_enviada', models.TextField(blank=True)),
                ('erro_envio', models.CharField(blank=True, max_length=255)),
                ('resposta_recebida', models.TextField(blank=True)),
                ('data_programada', models.DateTimeField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('cancelou_inscricao', models.BooleanField(default=False)),
                ('observacoes_internas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Envio de comunicacao',
                'verbose_name_plural': 'Envios de comunicacao',
            },
        ),
        migrations.AlterModelOptions(
            name='campanhacomunicacao',
            options={'verbose_name': 'Campanha de comunicacao', 'verbose_name_plural': 'Campanhas de comunicacao'},
        ),
        migrations.AlterModelOptions(
            name='listabloqueio',
            options={'verbose_name': 'Bloqueio de comunicacao', 'verbose_name_plural': 'Bloqueios de comunicacao'},
        ),
        migrations.AlterModelOptions(
            name='modelomensagem',
            options={'verbose_name': 'Modelo de mensagem', 'verbose_name_plural': 'Modelos de mensagem'},
        ),
        migrations.AddField(
            model_name='campanhacomunicacao',
            name='modelo_mensagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_comunicacao', to='comunicacao.modelomensagem'),
        ),
        migrations.AddField(
            model_name='campanhacomunicacao',
            name='observacoes_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campanhacomunicacao',
            name='permitir_cancelamento_inscricao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listabloqueio',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueios_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campanhacomunicacao',
            name='canal',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('notificacao_interna', 'Notificacao interna')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='campanhacomunicacao',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('enviando', 'Enviando'), ('concluida', 'Concluida'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='listabloqueio',
            name='canal',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('notificacao_interna', 'Notificacao interna')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='modelomensagem',
            name='canal',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('notificacao_interna', 'Notificacao interna')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='campanhacomunicacao',
            index=models.Index(fields=['nome'], name='comunicacao_nome_1e0ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='campanhacomunicacao',
            index=models.Index(fields=['canal', 'status'], name='comunicacao_canal_e0699e_idx'),
        ),
        migrations.AddIndex(
            model_name='campanhacomunicacao',
            index=models.Index(fields=['data_envio'], name='comunicacao_data_en_9fbf63_idx'),
        ),
        migrations.AddIndex(
            model_name='listabloqueio',
            index=models.Index(fields=['canal'], name='comunicacao_canal_e0ecb5_idx'),
        ),
        migrations.AddIndex(
            model_name='listabloqueio',
            index=models.Index(fields=['contato', 'canal'], name='comunicacao_contato_648a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='modelomensagem',
            index=models.Index(fields=['nome'], name='comunicacao_nome_4d8c04_idx'),
        ),
        migrations.AddIndex(
            model_name='modelomensagem',
            index=models.Index(fields=['canal'], name='comunicacao_canal_07f666_idx'),
        ),
        migrations.AddField(
            model_name='enviocomunicacao',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='enviocomunicacao',
            name='campanha_comunicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='comunicacao.campanhacomunicacao'),
        ),
        migrations.AddField(
            model_name='enviocomunicacao',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_comunicacao', to='eleitores.contatocrm'),
        ),
        migrations.AddField(
            model_name='enviocomunicacao',
            name='responsavel_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_comunicacao_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='enviocomunicacao',
            index=models.Index(fields=['status', 'canal'], name='comunicacao_status_b31bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='enviocomunicacao',
            index=models.Index(fields=['campanha_comunicacao', 'status'], name='comunicacao_campanh_67ce35_idx'),
        ),
        migrations.AddIndex(
            model_name='enviocomunicacao',
            index=models.Index(fields=['contato', 'canal'], name='comunicacao_contato_52ebee_idx'),
        ),
        migrations.AddConstraint(
            model_name='enviocomunicacao',
            constraint=models.UniqueConstraint(fields=('campanha_comunicacao', 'contato'), name='comunicacao_envio_unico_por_contato'),
        ),
    ]
