# Generated by Django 6.0.7 on 2026-07-28 18:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_initial'),
        ('comunicacao', '0004_enviocomunicacao_alter_campanhacomunicacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoInterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('titulo', models.CharField(max_length=160)),
                ('mensagem', models.TextField()),
                ('categoria', models.CharField(choices=[('agenda', 'Agenda'), ('comunicacao', 'Comunicacao'), ('equipe', 'Equipe'), ('financeiro', 'Financeiro'), ('lgpd', 'LGPD'), ('retencao', 'Retencao'), ('sistema', 'Sistema')], db_index=True, default='sistema', max_length=20)),
                ('url_destino', models.CharField(blank=True, max_length=255)),
                ('origem_modelo', models.CharField(blank=True, max_length=120)),
                ('origem_id', models.CharField(blank=True, max_length=64)),
                ('chave_unica', models.CharField(blank=True, max_length=140, null=True)),
                ('enviada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_internas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacao interna',
                'verbose_name_plural': 'Notificacoes internas',
                'indexes': [models.Index(fields=['usuario_destinatario', 'lida_em'], name='comunicacao_usuario_0de069_idx'), models.Index(fields=['categoria', 'criado_em'], name='comunicacao_categor_472a8b_idx'), models.Index(fields=['origem_modelo', 'origem_id'], name='comunicacao_origem__8f603a_idx')],
                'constraints': [models.UniqueConstraint(fields=('campanha', 'usuario_destinatario', 'chave_unica'), name='comunicacao_notificacao_chave_unica')],
            },
        ),
    ]
