# Generated by Django 6.0.7 on 2026-07-28 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_initial'),
        ('comunicacao', '0005_notificacaointerna'),
        ('eleitores', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhacomunicacao',
            name='erro_ultima_execucao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campanhacomunicacao',
            name='processamento_finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campanhacomunicacao',
            name='processamento_iniciado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campanhacomunicacao',
            name='provedor_ultimo_envio',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='campanhacomunicacao',
            name='ultima_execucao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviocomunicacao',
            name='identificador_externo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='enviocomunicacao',
            name='provedor_utilizado',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='enviocomunicacao',
            name='tentativas_envio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enviocomunicacao',
            name='ultima_tentativa_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enviocomunicacao',
            name='ultimo_erro_tecnico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='campanhacomunicacao',
            index=models.Index(fields=['status', 'ultima_execucao_em'], name='comunicacao_status_a05eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='enviocomunicacao',
            index=models.Index(fields=['status', 'ultima_tentativa_em'], name='comunicacao_status_23c60a_idx'),
        ),
    ]
