# Generated by Django 6.0.7 on 2026-07-28 18:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_initial'),
        ('comunicacao', '0006_campanhacomunicacao_erro_ultima_execucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroWebhookComunicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('notificacao_interna', 'Notificacao interna')], db_index=True, max_length=30)),
                ('provedor', models.CharField(blank=True, db_index=True, max_length=40)),
                ('evento', models.CharField(blank=True, db_index=True, max_length=60)),
                ('identificador_externo', models.CharField(blank=True, db_index=True, max_length=120)),
                ('dados_recebidos', models.JSONField(blank=True, default=dict)),
                ('assinatura_valida', models.BooleanField(db_index=True, default=False)),
                ('processado_com_sucesso', models.BooleanField(db_index=True, default=False)),
                ('mensagem_processamento', models.CharField(blank=True, max_length=255)),
                ('recebido_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks_comunicacao', to='campanhas.campanha')),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_registros', to='comunicacao.enviocomunicacao')),
            ],
            options={
                'verbose_name': 'Registro de webhook de comunicacao',
                'verbose_name_plural': 'Registros de webhook de comunicacao',
                'indexes': [models.Index(fields=['canal', 'recebido_em'], name='comunicacao_canal_d9e9f7_idx'), models.Index(fields=['provedor', 'evento'], name='comunicacao_provedo_44bb55_idx'), models.Index(fields=['identificador_externo', 'recebido_em'], name='comunicacao_identif_57912f_idx')],
            },
        ),
    ]
