# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCampanha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(db_index=True, max_length=80)),
                ('valor_esperado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('regiao', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(db_index=True, default='aberta', max_length=20)),
                ('percentual_conclusao', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas', to='equipe.integranteequipe')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
    ]
