# Generated by Django 6.0.7 on 2026-07-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacampanha',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('em_risco', 'Em risco'), ('concluida', 'Concluida'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='metacampanha',
            name='tipo',
            field=models.CharField(choices=[('novos_contatos', 'Novos contatos'), ('apoiadores_cadastrados', 'Apoiadores cadastrados'), ('liderancas_conquistadas', 'Liderancas conquistadas'), ('eventos_realizados', 'Eventos realizados'), ('participantes_eventos', 'Participantes em eventos'), ('voluntarios_cadastrados', 'Voluntarios cadastrados'), ('bairros_visitados', 'Bairros visitados'), ('municipios_visitados', 'Municipios visitados'), ('ligacoes_realizadas', 'Ligacoes realizadas'), ('mensagens_enviadas', 'Mensagens enviadas'), ('doacoes_registradas', 'Doacoes registradas'), ('tarefas_concluidas', 'Tarefas concluidas')], db_index=True, max_length=80),
        ),
    ]
