# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lideranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('nome_conhecido', models.CharField(blank=True, max_length=120)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('telefone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=30)),
                ('tipo_lideranca', models.CharField(choices=[('politica', 'Política'), ('comunitaria', 'Comunitária'), ('religiosa', 'Religiosa'), ('empresarial', 'Empresarial'), ('sindical', 'Sindical'), ('regional', 'Regional')], db_index=True, max_length=20)),
                ('organizacao', models.CharField(blank=True, max_length=255)),
                ('cargo_funcao', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(db_index=True, max_length=2)),
                ('cidade', models.CharField(db_index=True, max_length=120)),
                ('bairro', models.CharField(blank=True, db_index=True, max_length=120)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('regiao_eleitoral', models.CharField(blank=True, db_index=True, max_length=120)),
                ('zona_eleitoral', models.CharField(blank=True, max_length=20)),
                ('secao_eleitoral', models.CharField(blank=True, max_length=20)),
                ('apoiadores_estimados', models.PositiveIntegerField(default=0)),
                ('nivel_influencia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('estrategica', 'Estratégica')], default='media', max_length=20)),
                ('situacao_relacionamento', models.CharField(choices=[('novo_contato', 'Novo contato'), ('em_negociacao', 'Em negociação'), ('apoiador', 'Apoiador'), ('lideranca_confirmada', 'Liderança confirmada'), ('indeciso', 'Indeciso'), ('sem_interesse', 'Sem interesse'), ('inativo', 'Inativo')], db_index=True, default='novo_contato', max_length=25)),
                ('data_ultimo_contato', models.DateTimeField(blank=True, null=True)),
                ('proxima_acao', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='liderancas/fotos/')),
                ('consentimento_dados', models.BooleanField(default=False)),
                ('data_consentimento', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Liderança',
                'verbose_name_plural': 'Lideranças',
            },
        ),
        migrations.CreateModel(
            name='InteracaoLideranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('ligacao', 'Ligação'), ('mensagem', 'Mensagem'), ('visita', 'Visita'), ('compromisso', 'Compromisso')], max_length=20)),
                ('data_hora', models.DateTimeField()),
                ('resumo', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha')),
            ],
            options={
                'verbose_name': 'Interação com liderança',
                'verbose_name_plural': 'Interações com lideranças',
            },
        ),
    ]
