# Generated by Django 6.0.7 on 2026-07-28 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0002_initial'),
        ('liderancas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interacaolideranca',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_liderancas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='campanhas.campanha'),
        ),
        migrations.AddField(
            model_name='lideranca',
            name='responsavel_contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderancas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interacaolideranca',
            name='lideranca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='liderancas.lideranca'),
        ),
        migrations.AddIndex(
            model_name='lideranca',
            index=models.Index(fields=['nome_completo'], name='liderancas__nome_co_d08ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='lideranca',
            index=models.Index(fields=['telefone'], name='liderancas__telefon_e45d75_idx'),
        ),
        migrations.AddIndex(
            model_name='lideranca',
            index=models.Index(fields=['email'], name='liderancas__email_a36449_idx'),
        ),
        migrations.AddIndex(
            model_name='lideranca',
            index=models.Index(fields=['cidade', 'bairro'], name='liderancas__cidade_35b431_idx'),
        ),
    ]
